[package]
name = "ocipa/tiny-fsm"
version = "0.3.0"
license = "MIT"
authors = ["Ocipa <ocipamail@gmail.com>"]
description = "⚠️https://github.com/Ocipa/tinyFSM is in development, EVERYTHING is subject to change until v1.0.0⚠️ "
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = [
    "*.spec.lua", "*.spec.luau", "README.md", "assets",
    ".luaurc", ".gitignore", "aftman.toml", "selene.toml",
    "test.project.json", "sourcemap.json", ".vscode"
]

[dependencies]


[dev-dependencies]
TestEz = "roblox/testez@0.4.1"
